### ISSUE TITLE
Maplin don't appear to be selling the monitor anymore?

### ISSUE THREAD

**Issue by easaw** [jpsingleton/Raspberry-Pi-Electricity-Monitor#2]
http://www.maplin.co.uk/wireless-electricity-monitor-611581 is no longer there :(

Is there a model number so I can source this from ebay/ aliexpress or somewhere?

Last cached 2013 here: http://web.archive.org/web/20131009000629/http://www.maplin.co.uk/wireless-electricity-monitor-611581

Thank you

**Comment by jpsingleton** [comment]
Yeah, it's been discontinued. The only model number I can see is N94KQ and it looks like a custom Maplin branded [Sailwider](http://www.sailwider-smartpower.com/) product. You may have better luck with [OpenEnergyMonitor](https://openenergymonitor.org/emon/) or [geo](http://www.geotogether.com/).
